= Dataframes
:jbake-type: guide
:jbake-status: published
:jbake-tags: blog,asciidoc
:idprefix:
:parent:
:order: 2
:ordersub: 0

== Dataframes

The mkdocs executable is provided as an entry point and serve is the default command. If you're not familiar with Docker don't worry, we have you covered in the following sections.

Material for MkDocs can be directly used from GitHub by cloning the repository into a subfolder of your project root which might be useful if you want to use the very latest version:

== Create

**Nam id nisl** quam. Donec a lorem sit amet libero pretium vulputate vel ut purus. Suspendisse leo arcu,
mattis et imperdiet luctus, pulvinar vitae mi. Quisque fermentum sollicitudin feugiat. Mauris nec leo

=== First step

Code blocks and examples are an essential part of technical project documentation. Material for MkDocs provides different ways to set up syntax highlighting for code blocks, either during build time using Pygments or during runtime using a JavaScript syntax highlighter.

NOTE: Pygments or during runtime using a JavaScript syntax highlighter

The following sections discuss how to use different syntax highlighting features with Pygments, the recommended highlighter, so they don't apply when using a JavaScript syntax highlighter.

[source, groovy]
----
(0..20).each { n -> 
    println "number: $n"
}
----

=== Second Step

Code blocks can automatically render a button on the right side to allow the user to copy a code block's contents to the clipboard. Add the following to mkdocs.yml to enable them globally:

[source, groovy]
----
table         = table[table['SUGAR'] > 3 & table['FIBER'] in 2..5]
table['DIFF'] = table['SUGAR'] - table['FIBER']

table[0..10, ['ID', 'DIFF']]
----

== Second

ligula. Vestibulum tristique odio ut risus ultricies a hendrerit quam iaculis. Duis tempor elit sit amet
ligula vehicula et iaculis sem placerat. Fusce dictum, metus at volutpat lacinia, elit massa auctor risus,

== Third

id auctor arcu enim eu augue. Donec ultrices turpis in mi imperdiet ac venenatis sapien sodales. In
consequat imperdiet nunc quis bibendum. Nulla semper, erat quis ornare tristique, lectus massa posuere
libero, ut vehicula lectus nunc ut lorem. Aliquam erat volutpat.

== Filtering

Material for `MkDocs` is a theme for **MkDocs**, a static site generator geared towards (technical) project documentation. If you're familiar with Python, you can install Material for MkDocs with pip, the Python package manager. If not, we recommend using docker

[source, groovy]
.Groovy code
----
@Grab('com.blabla.tablesaw:tablesaw-core:1.0.0')
import com.blabla.tablesaw.Table

table = Table.read().csv('moneyball')
table = table["SUGAR"] > 3 & table['FIBER'] > 10
table = table[0..-1, ['ID', 'SUGAR', 'FIBER']]
----

=== Linux

This will automatically install compatible versions of all dependencies: **MkDocs, Markdown, Pygments and Python** Markdown Extensions. Material for MkDocs always strives to support the latest versions, so there's no need to install those packages separately.

[source, groovy]
----
table['DIFF'] = table['SUGAR'] - table['FIBER']
----

=== Windows

Tip: If you don't have prior experience with Python, we recommend reading Using Python's pip to Manage Your Projects' Dependencies, which is a really good introduction on the mechanics of Python package management and helps you troubleshoot if you run into errors.

[source, groovy]
----
table['ID']
----

== Getting Started

The mkdocs executable is provided as an entry point and serve is the default command. If you're not familiar with Docker don't worry, we have you covered in the following sections.

- http://google.com[mkdocs-minify-plugin]
- mkdocs-amio
- mkdocs-juao
- mkdocs-redirects

Material for MkDocs can be directly used from GitHub by cloning the repository into a subfolder of your project root which might be useful if you want to use the very latest version:

[source, shell]
----
git clone https://github.com/squidfunk/mkdocs-material.git
----

Before settling for Material for MkDocs, it's a good idea to understand the philosophy behind the project, in order to make sure it aligns with your goals. This page explains the design principles anchored in Material for MkDocs, and discusses the conventions used in this documentation.
